apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: cluster-manager
  labels:
    type: basic-service
    name: mysql-service
spec:
  ports:
    - port: 3306
  selector:
    type: basic-service
    name: mysql-service
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-service
  namespace: cluster-manager
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      type: basic-service
      name: mysql-service
  template:
    metadata:
      labels:
        type: basic-service
        name: mysql-service
    spec:
      containers:
      - name: mysql-service
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: "mysql-persistent-storage"
        hostPath:
          path: "/tmp/privatetest/clustermanager/mysql"
